version: '3'

services:
  redis:
    image: redis:alpine
    deploy:
        mode: replicated
        replicas: 1
    ports:
      - "6379:6379"
    networks:
      - mynet

  web:
    build: .
    image: 127.0.0.1:5000/myapp:latest
    deploy:
      mode: global
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - mynet

networks:
  mynet:
